### ISSUE TITLE
git error "fatal: ambiguous argument '<branch name>' " occurred in set_current_revision task

### ISSUE THREAD

**Issue by tette** [ydkn/capistrano-git-copy#10]
When I was set specify a non master branch(named `develop`) to `:branch` in `config/deploy.rb`, got an error that the following occurred in the `git_copy_utility.fetch_revision` method execution.

I have faced this issue in Git 2.4.1 in OS X Yosemite

```
DEBUG [f4a26bd6] Running /usr/bin/env git rev-list --max-count=1 --abbrev-commit develop as tette@localhost
DEBUG [f4a26bd6] Command: cd /var/folders/78/sy6td1pn43d_l0f6z_bw5kf00000gq/T/my_app_name_develop_21d188aa_6c2fae3f/repo && /usr/bin/env git rev-list --max-count=1 --abbrev-commit develop
DEBUG [f4a26bd6] 	fatal: ambiguous argument 'develop': unknown revision or path not in the working tree.
DEBUG [f4a26bd6] 	Use '--' to separate paths from revisions, like this:
DEBUG [f4a26bd6] 	'git <command> [<revision>...] -- [<file>...]'
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Command::Failed: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: ambiguous argument 'develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Tasks: TOP => git_copy:set_current_revision
(See full trace by running task with --trace)
The deploy has failed with an error: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: ambiguous argument 'develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Perhaps this problem occurs because it does not specify a branch when it clone the repository.
As the result, specified branch does not exist branch in local repository, I think.

I think that it works well If you add the branch specified options to "git clone" command arguments to the method.

**Comment by ydkn** [comment]
You're right, calling rev-list on the cloned repository won't work with a branch name.
Cloning the repository is not performed every time you deploy, so instead of clone the configured branch I use the commit hash for the branch which is determined more securely.

Can you please check if branch _fetch_revision_fix_ (be9c76796def6944ca56b8f4bb493344ea612f16) solves the problem?

**Comment by tette** [comment]
Looks good to me.
Your branch *fetch_revision_fix* solves this problem. Thank you.

**Comment by ydkn** [comment]
Thanks for the feedback.
I merge it and made a new release (1.0.2)
