### ISSUE TITLE
Every tasks are executed twice

### ISSUE THREAD

**Issue by abouillis** [ydkn/capistrano-git-copy#17]
Hello,

after installation and some deployment tests, every git-copy tasks seems to be executed twice.

I've check my configuration, everything seems to be ok.

My capistrano version: 3.4.0

Thank you for your advice.

**Comment by ydkn** [comment]
The only case I can think of that this happens is that the gem is required multiple times in _Capfile_.
I change a few things to avoid that this happens. Can you please give the current master (ffa6f5cb9ea6891d734d0965ae1da50fb49b85e9) a try if it is now only executed once in your setup.

**Comment by abouillis** [comment]
That seems ok with the current master.

Can you push that fix to rubygems?

Thanks!

**Comment by ydkn** [comment]
Just released v1.1.0.
