### ISSUE TITLE
How to conditionally exclude file?

### ISSUE THREAD

**Issue by randoum** [ydkn/capistrano-git-copy#18]
Greetings,

Using `.gitattributes` successfully to exclude files from the deploy archive; I need to exclude a file (i.e *config/schedule.rb*) only for staging environment deployment.

Any pointer on how to do this?
Thanks

**Comment by randoum** [comment]
@ydkn Any insights ? Thanks

**Comment by ydkn** [comment]
Hi,

currently the only way to exclude files is through `.gitattributes`.
Before I figured out that `git-archive-all` supports `.gitattributes` I thought of adding a config variable to list files/directories to exclude.
What are your thoughts on a config option for additional exclusion?

**Comment by ydkn** [comment]
I put that into a branch (`git_excludes`) - check it out if you like.
Instructions are in the README.

**Comment by randoum** [comment]
Hi,

Just had a quick look at your branch, looks good.
I'm in a middle of something I cannot interrupt for now, so I'll test it as soon as I can.
Will get back to you.

Cheers

**Comment by ydkn** [comment]
The _git_excludes_ option is know available starting with v1.2.0
