### ISSUE TITLE
undefined method 'tmpdir' for Dir:class

### ISSUE THREAD

**Issue by thedarkside** [ydkn/capistrano-git-copy#22]
i am running ruby 2.3.1 and it seems that capistrano-git-copy does not `require 'tmpdir'` which leads to that error: `undefined method 'tmpdir' for Dir:class`. 
Placing that require statement in deploy.rb before `require 'capistrano/git_copy'` solves this but it would be much nicer if it would be required where it should be: `capistrano-git-copy-1.3.0/lib/capistrano/git_copy/scm.rb:132`

**Comment by ydkn** [comment]
Thanks you for reporting this. I just fixed and released it.
