### ISSUE TITLE
.gitattributes export-ignore works only :with_submodules, false

### ISSUE THREAD

**Issue by swobspace** [ydkn/capistrano-git-copy#23]
git-archive-all seems not respecting .gittatributes with export-ignore. Disabling submodules uses plain git archive and all works correct. I don't need submodules, but submodules = true is default.

wob

**Comment by ydkn** [comment]
This is tracked at https://github.com/Kentzo/git-archive-all/issues/18

I do not intend to do some workaround in this gem so we have to wait on _git-archive-all_.

But I'm going to add information about this to the readme.

**Comment by swobspace** [comment]
My intention for this issue was primarily to prevent others to be trapped.

**Comment by ydkn** [comment]
Issue was resolved in https://github.com/Kentzo/git-archive-all/pull/40
