### ISSUE TITLE
export-ignore ignored

### ISSUE THREAD

**Issue by randoum** [ydkn/capistrano-git-copy#8]
Greetings,

Export ignore instructions from `.gitattributes` are ignored during deploy

Steps to reproduce:
- Create `.gitattributes`file at your project root, with the following content: `spec export-ignore` (you can adapt the folder name)
- Ensure that `.gitignore` file does not exclude the newly created `.gitattributes` file
- Commit to git
- Deploy

-> result the spec folder is deployed

**Comment by ydkn** [comment]
Hi,

this is actually a problem with _git-archive-all_ which only works with regular expressions: https://github.com/Kentzo/git-archive-all/blob/master/git-archive-all#L227

If you change _spec export-ignore_ to _spec/* export-ignore_ it should work.

**Comment by randoum** [comment]
Thanks for the pointer
